# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'package'

# - task: Docker@2
#   inputs:
#     containerRegistry: 'dockerhub'
#     repository: 'balaji36490/tomcat'
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
- task: CmdLine@2
  inputs:
    script: |
      git config --global user.email "sivabalaji.280@gmail.com"
      git config --global user.name "Siva Balaji"
      sed -i "s/tomcat:8.0/tomcat:$(Build.BuildId)/g" kubernetes/deployment.yaml
      git add -A
      git commit -m "updating the tag"
      git push https://github.com/sivabalaji280/simplewarfile.git
